#!/bin/bash

# 参数1：项目名（必填）
PROJECT_NAME=$1
# 默认保存路径：用户根目录（/Users/Everest）
SAVE_PATH="${HOME}/${PROJECT_NAME}"

# 创建目录结构
mkdir -p ${SAVE_PATH}/{src,lib,docs,data} && \
touch ${SAVE_PATH}/src/main.ino && \
touch ${SAVE_PATH}/README.md && \
echo "# Arduino项目忽略文件
.idea/
*.hex
*.elf" > ${SAVE_PATH}/.gitignore

echo "项目已生成 → ${SAVE_PATH}
